#!/usr/bin/with-contenv bashio
# ==============================================================================
# Generate /etc/tor/torrc from add-on options
# ==============================================================================
set -e

CONFIG_PATH="/etc/tor/torrc"
BRIDGES_ENABLED="$(bashio::config 'bridges_enabled')"
BRIDGES="$(bashio::config 'bridges')"
LOG_LEVEL="$(bashio::config 'log_level')"

bashio::log.info "Generating Tor configuration..."

mkdir -p /var/lib/tor /var/log/tor /data/onionshare
chown -R tor:tor /var/lib/tor /var/log/tor

# Map our log_level to Tor's syntax
case "${LOG_LEVEL}" in
    trace|debug)  TOR_LOG="debug" ;;
    info)         TOR_LOG="info"  ;;
    notice)       TOR_LOG="notice" ;;
    warning)      TOR_LOG="warn"  ;;
    error|fatal)  TOR_LOG="err"   ;;
    *)            TOR_LOG="notice" ;;
esac

cat > "${CONFIG_PATH}" <<EOF
# Auto-generated by OnionShare add-on - do not edit by hand
User tor
DataDirectory /var/lib/tor
PidFile /var/run/tor/tor.pid
RunAsDaemon 0

# SOCKS proxy for onionshare-cli
SocksPort 127.0.0.1:9050

# Control port for onionshare to manage hidden services
ControlPort 127.0.0.1:9051
CookieAuthentication 1
CookieAuthFile /var/lib/tor/control_auth_cookie
CookieAuthFileGroupReadable 1

Log ${TOR_LOG} file /var/log/tor/tor.log
Log notice stdout

# Disable the Tor relay role - we only need client mode
ClientOnly 1
EOF

if bashio::var.true "${BRIDGES_ENABLED}" && bashio::var.has_value "${BRIDGES}"; then
    bashio::log.info "Bridges enabled - appending bridge configuration"
    cat >> "${CONFIG_PATH}" <<EOF

UseBridges 1
EOF
    # Each non-empty line in BRIDGES is a Bridge line
    echo "${BRIDGES}" | while IFS= read -r line; do
        [ -n "$line" ] && echo "Bridge $line" >> "${CONFIG_PATH}"
    done
fi

mkdir -p /var/run/tor
chown tor:tor /var/run/tor

bashio::log.info "Tor configuration written to ${CONFIG_PATH}"
